using Packet.SoundModem.Ardop;
using Packet.SoundModem.Fec;

namespace Packet.SoundModem.Tests.Ardop;

/// <summary>
/// Rung 0 of the ARDOP validation ladder (docs/ardop-design.md §6.2): byte-exactness of
/// the CRC-16 (the nonstandard 0x8810/LSB-injection formulation), the CRC-8 session ID,
/// the frame-type parity symbol and the Reed-Solomon parity against vectors produced by
/// ardopcf's own source — <c>samples/ardop/ardop-reference-vectors.txt</c>, generated by
/// <c>gen-reference-vectors.c</c> compiling the reference's verbatim CRC functions and
/// its actual <c>lib/rockliff/rrs.c</c> codec (see samples/ardop/PROVENANCE.md).
/// </summary>
public class ArdopReferenceVectorTests
{
    private static string[] Vectors() =>
        File.ReadAllLines(Path.Combine(SamplesDir(), "ardop-reference-vectors.txt"))
            .Where(line => !line.StartsWith('#') && line.Length > 0)
            .ToArray();

    private static byte[] FromHex(string hex) => Convert.FromHexString(hex);

    [Fact]
    public void Crc16_Matches_Ardopcf_GenCRC16()
    {
        var vectors = Vectors().Where(l => l.StartsWith("crc16 ", StringComparison.Ordinal)).ToArray();
        vectors.Should().NotBeEmpty();

        foreach (string line in vectors)
        {
            string[] parts = line.Split(' ');
            ArdopCrc.Crc16(FromHex(parts[1])).Should().Be(
                Convert.ToUInt16(parts[2], 16), "vector: {0}", line);
        }
    }

    [Fact]
    public void Crc8_Matches_Ardopcf_GenCRC8()
    {
        var vectors = Vectors().Where(l => l.StartsWith("crc8 ", StringComparison.Ordinal)).ToArray();
        vectors.Should().NotBeEmpty();

        foreach (string line in vectors)
        {
            string[] parts = line.Split(' ');
            ArdopCrc.Crc8(System.Text.Encoding.ASCII.GetBytes(parts[1])).Should().Be(
                Convert.ToByte(parts[2], 16), "vector: {0}", line);
        }
    }

    [Fact]
    public void Type_Parity_Matches_Ardopcf_For_All_256_Types()
    {
        var vectors = Vectors().Where(l => l.StartsWith("parity ", StringComparison.Ordinal)).ToArray();
        vectors.Should().HaveCount(256);

        foreach (string line in vectors)
        {
            string[] parts = line.Split(' ');
            ArdopFrameType.TypeParity(Convert.ToByte(parts[1], 16)).Should().Be(
                byte.Parse(parts[2]), "vector: {0}", line);
        }
    }

    [Fact]
    public void Reed_Solomon_Parity_Matches_Rockliff_Rs_Append_Byte_Exact()
    {
        // The design's claim that our FX.25 RS configuration (GF 0x11D, fcr = 1) covers
        // ardopcf's rrs.c holds — through the Rockliff wire-layout mapping in
        // ArdopFrameCodec.RsAppend (byte-reversed codeword, zero-pad clocked through
        // the LFSR). Proved byte-for-byte across every Phase A geometry
        // (docs/ardop-design.md §3.5).
        var vectors = Vectors().Where(l => l.StartsWith("rs ", StringComparison.Ordinal)).ToArray();
        vectors.Should().NotBeEmpty();

        foreach (string line in vectors)
        {
            string[] parts = line.Split(' ');
            int rsLen = int.Parse(parts[2]);
            byte[] data = FromHex(parts[3]);
            byte[] expectedParity = FromHex(parts[4]);

            var block = new byte[data.Length + rsLen];
            data.CopyTo(block, 0);
            ArdopFrameCodec.RsAppend(block, data.Length, rsLen);
            block[data.Length..].Should().Equal(expectedParity, "vector: {0}", line);
        }
    }

    [Fact]
    public void Reed_Solomon_Corrects_Up_To_Half_Parity_Errors_On_Reference_Codewords()
    {
        foreach (string line in Vectors().Where(l => l.StartsWith("rs ", StringComparison.Ordinal)))
        {
            string[] parts = line.Split(' ');
            int rsLen = int.Parse(parts[2]);
            byte[] codeword = [.. FromHex(parts[3]), .. FromHex(parts[4])];
            byte[] corrupted = (byte[])codeword.Clone();
            for (int e = 0; e < rsLen / 2; e++)
            {
                corrupted[e * 7 % (codeword.Length - rsLen)] ^= (byte)(0x5A + e);
            }

            ArdopFrameCodec.RsCorrect(corrupted, rsLen).Should().Be(rsLen / 2, "vector: {0}", line);
            corrupted.Should().Equal(codeword);
        }
    }

    internal static string SamplesDir()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "pdn-soundmodem.slnx")))
        {
            dir = dir.Parent;
        }

        string root = dir?.FullName ?? throw new InvalidOperationException("repo root not found");
        return Path.Combine(root, "samples", "ardop");
    }
}
