"""
Multi-frame BCJR equalization prototype for MS110D Poor channel.

Question: does processing all 128 frames (12,288 symbols) jointly with the
BCJR give better raw BER than per-frame BCJR (96 symbols)?

Channel: 2-path Rayleigh, 2 ms delay (L=5 at 2400 Bd), 0.5 Hz Doppler
(1 Hz two-sigma), Gaussian Doppler filtering.
Waveform: WN4-like BPSK, U=96 data + K=32 probe per frame, 128 frames/block.
SNR: +10 dB in 3 kHz.

Channel model used by the BCJR:
    y[n] = h1[frame] * x[n] + h2[frame] * x[n-L] + w[n]
with h1, h2 estimated per-frame from the known probe (oracle-ish LS).

Log-domain forward-backward algorithm, 32 states (2^L, L=5).
"""
import numpy as np
from scipy.special import logsumexp

# --- Parameters ---
SNR_DB = 10.0
U_DATA = 96          # data symbols per frame
K_PROBE = 32         # probe symbols per frame
FRAME_LEN = U_DATA + K_PROBE
N_FRAMES = 128
N_TOTAL = N_FRAMES * FRAME_LEN          # 16384 symbols (probe+data)
N_DATA_TOTAL = N_FRAMES * U_DATA        # 12288 data symbols
SYMBOL_RATE = 2400
DOPPLER_HZ = 0.5     # one-sigma (1 Hz two-sigma)
DELAY_MS = 2.0
L = 5                # channel memory: 2 ms * 2400 Bd = 4.8 -> 5
N_STATES = 1 << L    # 32
BW_HZ = 3000.0
KNOWN_LLR = 30.0     # magnitude of prior LLR for known (probe) symbols

# BPSK mapping: bit 0 -> +1, bit 1 -> -1
BPSK = np.array([1.0, -1.0])


# --- Channel generation ---
def rayleigh_gaussian_doppler(n, sigma_f, fs, rng):
    """Complex Rayleigh process with Gaussian Doppler PSD.

    Generated by filtering white complex Gaussian noise with a Gaussian
    filter whose frequency response is exp(-f^2/(2*sigma_f^2)).
    sigma_f is the one-sigma Doppler spread (Hz).
    """
    white = (rng.standard_normal(n) + 1j * rng.standard_normal(n)) / np.sqrt(2)
    if sigma_f <= 0:
        return white
    # Filter in frequency domain. Use a large FFT for fine frequency
    # resolution (the Doppler filter is very narrow: sigma_f/fs ~ 2e-4).
    nfft = 1 << max(int(n - 1).bit_length(), 18)
    f = np.fft.fftfreq(nfft, d=1.0 / fs)
    H = np.exp(-(f ** 2) / (2.0 * sigma_f ** 2))
    kernel = np.fft.ifft(H)
    # Make a centered, truncated kernel
    kh = np.fft.fftshift(kernel)
    mid = len(kh) // 2
    half = min(2000, mid)
    k = kh[mid - half:mid + half + 1]
    k = k / np.sqrt(np.sum(np.abs(k) ** 2))   # unit-power output
    out = np.convolve(white, k, mode='same')
    # Normalize empirical power to 1
    out = out / np.sqrt(np.mean(np.abs(out) ** 2))
    return out


def generate_channel(n, rng):
    """2-path Rayleigh channel: returns (h1, h2) per-symbol complex gains."""
    # Independent fading on each path
    h1 = rayleigh_gaussian_doppler(n, DOPPLER_HZ, SYMBOL_RATE, rng)
    h2 = rayleigh_gaussian_doppler(n, DOPPLER_HZ, SYMBOL_RATE, rng)
    # Equal average power per path (E[|h1|^2]=E[|h2|^2]=1)
    return h1, h2


def apply_channel(x, h1, h2, snr_db, rng):
    """y[n] = h1[n] x[n] + h2[n] x[n-L] + w[n]."""
    n = len(x)
    x_delayed = np.zeros(n, dtype=complex)
    x_delayed[L:] = x[:-L]
    sig = h1 * x + h2 * x_delayed
    # SNR per symbol: signal power ~ E[|h1 x + h2 x_d|^2] = 2 (unit-power paths)
    sig_power = 2.0
    noise_power = sig_power / (10 ** (snr_db / 10.0))
    sigma = np.sqrt(noise_power / 2.0)
    w = sigma * (rng.standard_normal(n) + 1j * rng.standard_normal(n)) / np.sqrt(2)
    return sig + w, sigma


# --- Per-frame channel estimation from probe (oracle known probe symbols) ---
def estimate_channel_frame(y_frame, x_frame):
    """LS estimate of (h1, h2) for one frame using the K_PROBE probe symbols.

    Uses the probe portion. We need x[n-L] which may reach into the previous
    frame; the caller passes a full x_frame that includes L warmup symbols
    prepended (length FRAME_LEN + L), and y aligned likewise.
    """
    # Probe occupies indices [L, L+K_PROBE) in the warmed-up frame so that
    # x[n-L] is available and known for every probe symbol.
    idx = np.arange(L, L + K_PROBE)
    a = x_frame[idx]            # x[n]
    b = x_frame[idx - L]        # x[n-L]
    A = np.column_stack([a, b])
    sol, *_ = np.linalg.lstsq(A, y_frame[idx], rcond=None)
    return sol[0], sol[1]


# --- Trellis precomputation ---
def build_trellis():
    """State = last L bits packed: bit0 = x[n-1] (newest), bit L-1 = x[n-L].

    next_state given input bit b (x[n]=b):
        new state bit0 = b, shift others down.
    oldest bit (x[n-L]) = bit (L-1) of current state.
    """
    next_state = np.zeros((N_STATES, 2), dtype=np.int32)
    oldest = np.zeros(N_STATES, dtype=np.int32)
    for s in range(N_STATES):
        oldest[s] = (s >> (L - 1)) & 1
        for b in range(2):
            # shift: drop oldest, move bits down, insert b at position 0
            ns = ((s << 1) & (N_STATES - 1)) | b
            next_state[s, b] = ns
    return next_state, oldest


NEXT_STATE, OLDEST = build_trellis()
# Successors of each SOURCE state s (row s): NEXT_STATE[s, b] = ((s<<1)&mask)|b.
# Branch metric is SOURCE-indexed: the branch out of source state s with input
# bit b emits x[n] = 1-2*b and uses the delayed symbol x[n-L] = OLDEST[s]
# (bit L-1 of the source state, which encodes x[n-1]..x[n-L]).
XN_INPUT = np.array([1.0, -1.0])           # x[n] for input bit b (= 1-2*b)
XD_SOURCE = 1 - 2 * OLDEST                 # x[n-L] for branch out of source s


# --- Log-domain BCJR ---
def bcjr_log(y, h1, h2, prior_llr, sigma):
    """Log-domain forward-backward.

    y: observations (complex), length N
    h1, h2: per-symbol channel (complex), length N (may be piecewise const)
    prior_llr: per-symbol prior LLR ln P(b=0)/P(b=1), length N
    sigma: noise std (per real/imag dim)

    Returns posterior LLR per symbol (extrinsic+prior combined).
    """
    N = len(y)
    S = N_STATES
    succ0 = NEXT_STATE[:, 0]                 # successor of source s with b=0
    succ1 = NEXT_STATE[:, 1]                 # successor of source s with b=1

    alpha = np.full((N + 1, S), -np.inf)
    alpha[0, 0] = 0.0                        # start in all-zeros state
    beta = np.full((N + 1, S), -np.inf)
    beta[N, :] = 0.0                         # uniform terminal

    # log_gamma[n, s, b] = branch metric out of source state s with input bit b
    log_gamma = np.empty((N, S, 2))

    xd = XD_SOURCE                           # (S,) x[n-L] per source state
    for n in range(N):
        for b in range(2):
            xn = XN_INPUT[b]
            mu = h1[n] * xn + h2[n] * xd     # (S,)
            fit = (2.0 * np.real(y[n] * np.conj(mu)) - np.abs(mu) ** 2) / (sigma ** 2)
            prior_term = (0.5 - b) * prior_llr[n]
            log_gamma[n, :, b] = fit + prior_term

        # Forward scatter: alpha[n+1, ns] = logsumexp over (s,b) with NEXT[s,b]=ns
        lg0 = log_gamma[n, :, 0]
        lg1 = log_gamma[n, :, 1]
        a_next = np.full(S, -np.inf)
        np.logaddexp.at(a_next, succ0, alpha[n] + lg0)
        np.logaddexp.at(a_next, succ1, alpha[n] + lg1)
        m = np.max(a_next)
        if np.isfinite(m):
            a_next -= m
        alpha[n + 1] = a_next

    for n in range(N - 1, -1, -1):
        # Backward: beta[n, s] = logsumexp_b ( metric[s,b] + beta[n+1, NEXT[s,b]] )
        v0 = log_gamma[n, :, 0] + beta[n + 1, succ0]
        v1 = log_gamma[n, :, 1] + beta[n + 1, succ1]
        beta[n] = np.logaddexp(v0, v1)
        m = np.max(beta[n])
        if np.isfinite(m):
            beta[n] -= m

    # Posterior for x[n]: state at time n+1 has x[n] in bit 0.
    log_post = alpha[1:] + beta[1:]          # (N, S)
    states_b0 = np.arange(S)[(np.arange(S) & 1) == 0]
    states_b1 = np.arange(S)[(np.arange(S) & 1) == 1]
    llr = (logsumexp(log_post[:, states_b0], axis=1)
           - logsumexp(log_post[:, states_b1], axis=1))
    return llr


# --- Main experiment ---
def run(seed=12345):
    rng = np.random.default_rng(seed)

    # Random BPSK data bits for the whole block (probe + data per frame)
    bits = rng.integers(0, 2, size=N_TOTAL)
    x = 1 - 2 * bits.astype(float)            # BPSK symbols

    # Generate channel and observations
    h1, h2 = generate_channel(N_TOTAL, rng)
    y, sigma = apply_channel(x, h1, h2, SNR_DB, rng)

    # Per-frame channel estimates from probe (oracle probe symbols known)
    h1_est = np.zeros(N_TOTAL, dtype=complex)
    h2_est = np.zeros(N_TOTAL, dtype=complex)
    for fr in range(N_FRAMES):
        s = fr * FRAME_LEN
        # warmed-up slice for estimation (need x[n-L])
        x_warm = np.zeros(FRAME_LEN + L, dtype=complex)
        x_warm[:L] = x[s - L:s] if s >= L else 0.0
        x_warm[L:] = x[s:s + FRAME_LEN]
        y_warm = np.zeros(FRAME_LEN + L, dtype=complex)
        y_warm[L:] = y[s:s + FRAME_LEN]
        c1, c2 = estimate_channel_frame(y_warm, x_warm)
        h1_est[s:s + FRAME_LEN] = c1
        h2_est[s:s + FRAME_LEN] = c2

    # Build prior LLR: probe symbols known, data symbols unknown (0)
    prior = np.zeros(N_TOTAL)
    for fr in range(N_FRAMES):
        s = fr * FRAME_LEN
        probe_bits = bits[s:s + K_PROBE]
        prior[s:s + K_PROBE] = KNOWN_LLR * (1 - 2 * probe_bits)  # +L for bit0, -L for bit1

    data_mask = np.zeros(N_TOTAL, dtype=bool)
    for fr in range(N_FRAMES):
        s = fr * FRAME_LEN + K_PROBE
        data_mask[s:s + U_DATA] = True

    # ---- Multi-frame BCJR: all N_TOTAL symbols jointly ----
    llr_multi = bcjr_log(y, h1_est, h2_est, prior, sigma)
    hat_multi = (llr_multi < 0).astype(int)   # LLR<0 -> bit 1
    err_multi = np.count_nonzero((hat_multi != bits) & data_mask)
    ber_multi = err_multi / N_DATA_TOTAL

    # ---- Per-frame BCJR: each frame independently ----
    err_pf = 0
    for fr in range(N_FRAMES):
        s = fr * FRAME_LEN
        yf = y[s:s + FRAME_LEN]
        h1f = h1_est[s:s + FRAME_LEN]
        h2f = h2_est[s:s + FRAME_LEN]
        pf = prior[s:s + FRAME_LEN]
        llr_f = bcjr_log(yf, h1f, h2f, pf, sigma)
        hat_f = (llr_f < 0).astype(int)
        bf = bits[s:s + FRAME_LEN]
        # data portion of this frame
        err_pf += np.count_nonzero(hat_f[K_PROBE:] != bf[K_PROBE:])
    ber_pf = err_pf / N_DATA_TOTAL

    # ---- Hard-slice reference (no equalization) ----
    # naive: divide by h1 and slice
    z = y / h1_est
    hat_hard = (np.real(z) < 0).astype(int)
    ber_hard = np.count_nonzero((hat_hard != bits) & data_mask) / N_DATA_TOTAL

    print("=" * 60)
    print("Multi-frame BCJR prototype - MS110D Poor channel (WN4-like)")
    print("=" * 60)
    print(f"Frames={N_FRAMES}, U={U_DATA}, K={K_PROBE}, L={L}, states={N_STATES}")
    print(f"SNR={SNR_DB} dB, Doppler={DOPPLER_HZ} Hz, delay={DELAY_MS} ms")
    print(f"Total data symbols: {N_DATA_TOTAL}")
    print("-" * 60)
    print(f"Hard-slice (y/h1) raw BER : {ber_hard:.4e}  "
          f"({int(ber_hard*N_DATA_TOTAL)} errors)")
    print(f"Per-frame BCJR raw BER    : {ber_pf:.4e}  "
          f"({err_pf} errors / {N_DATA_TOTAL})")
    print(f"Multi-frame BCJR raw BER  : {ber_multi:.4e}  "
          f"({err_multi} errors / {N_DATA_TOTAL})")
    print("-" * 60)
    if ber_multi > 0:
        print(f"Improvement factor (per-frame / multi-frame): "
              f"{ber_pf / ber_multi:.2f}x")
    else:
        print("Multi-frame BCJR: zero errors (improvement factor -> inf)")
    print("=" * 60)
    return ber_pf, ber_multi


if __name__ == "__main__":
    seeds = [12345, 7, 99, 2024, 555]
    pfs, mfs = [], []
    for sd in seeds:
        pf, mf = run(seed=sd)
        pfs.append(pf)
        mfs.append(mf)
    print()
    print("Summary over %d channel realizations:" % len(seeds))
    print("  per-frame   BERs:", ["%.2e" % p for p in pfs])
    print("  multi-frame BERs:", ["%.2e" % m for m in mfs])
    print("  mean per-frame   raw BER: %.3e" % np.mean(pfs))
    print("  mean multi-frame raw BER: %.3e" % np.mean(mfs))
    print("  mean improvement factor : %.2fx" % (np.mean(pfs) / np.mean(mfs)))
