#!/usr/bin/env python3
"""Transliterate FreeDV/codec2 LDPC parity-check matrices (and the built-in decode
oracle vectors) into C#. Run once at authoring time; the output .g.cs files are committed.

The five datac LDPC codes and their sparse H-matrices come from drowe67/codec2
(codec2 1.2.0, git 310777b), LGPL-2.1 — see docs/ofdm-design.md §1.4 / §5 and PROVENANCE.md.
Nothing is hand-copied: this script parses the .h defines and the .c const arrays and asserts
the column-major dimensions (M*max_row_weight, K*max_col_weight) so a wrong parse fails loudly.

Usage:  gen.py <codec2-src-dir> <pdn-repo-root>
"""
import re, sys, os

CODES = ["H_128_256_5", "H_256_512_4", "H_1024_2048_4f", "H_4096_8192_3d", "HRA_56_56"]
DEFINES = ["NUMBERPARITYBITS", "MAX_ROW_WEIGHT", "CODELENGTH",
           "NUMBERROWSHCOLS", "MAX_COL_WEIGHT", "MAX_ITER"]


def parse_h(path, name):
    txt = open(path).read()
    d = {}
    for key in DEFINES:
        m = re.search(rf"#define\s+{re.escape(name)}_{key}\s+(\d+)", txt)
        if not m:
            raise SystemExit(f"{name}: missing #define {key}")
        d[key] = int(m.group(1))
    return d


def array_body(txt, name, arr):
    m = re.search(rf"{re.escape(name)}_{arr}\s*\[\]\s*=\s*\{{(.*?)\}}", txt, re.S)
    return m.group(1) if m else None


def ints(body):
    return [int(x) for x in re.findall(r"-?\d+", body)]


def floats(body):
    # codec2 floats may carry an 'f' suffix and/or scientific notation
    return [float(x.rstrip("fF")) for x in re.findall(r"-?\d+\.?\d*(?:[eE][+-]?\d+)?f?", body)]


def emit_ushorts(vals, indent="        "):
    out = []
    for i in range(0, len(vals), 20):
        out.append(indent + ", ".join(str(v) for v in vals[i:i + 20]) + ",")
    return "\n".join(out)


def emit_floats(vals, indent="        "):
    out = []
    for i in range(0, len(vals), 12):
        chunk = ", ".join(f"{v!r}f" for v in vals[i:i + 12])
        out.append(indent + chunk + ",")
    return "\n".join(out)


def emit_bytes(vals, indent="        "):
    out = []
    for i in range(0, len(vals), 40):
        out.append(indent + ", ".join(str(v) for v in vals[i:i + 40]) + ",")
    return "\n".join(out)


def main():
    src, root = sys.argv[1], sys.argv[2]
    tables, oracles = [], []
    for name in CODES:
        d = parse_h(os.path.join(src, name + ".h"), name)
        M, K, N = d["NUMBERPARITYBITS"], d["NUMBERROWSHCOLS"], d["CODELENGTH"]
        c = open(os.path.join(src, name + ".c")).read()
        rows = ints(array_body(c, name, "H_rows"))
        cols = ints(array_body(c, name, "H_cols"))
        # the guardrail: column-major sparse dims must be exact
        assert len(rows) == M * d["MAX_ROW_WEIGHT"], \
            f"{name}: H_rows {len(rows)} != M*maxrow {M * d['MAX_ROW_WEIGHT']}"
        assert len(cols) == K * d["MAX_COL_WEIGHT"], \
            f"{name}: H_cols {len(cols)} != K*maxcol {K * d['MAX_COL_WEIGHT']}"

        tables.append(f"""    internal static class {name}
    {{
        public const int NumberParityBits = {M}, MaxRowWeight = {d['MAX_ROW_WEIGHT']},
            CodeLength = {N}, NumberRowsHcols = {K}, MaxColWeight = {d['MAX_COL_WEIGHT']},
            MaxIter = {d['MAX_ITER']};

        public static readonly ushort[] HRows =
        {{
{emit_ushorts(rows)}
        }};

        public static readonly ushort[] HCols =
        {{
{emit_ushorts(cols)}
        }};
    }}""")

        inp = array_body(c, name, "input")
        det = array_body(c, name, "detected_data")
        if inp is not None and det is not None:
            fin, bdet = floats(inp), ints(det)
            assert len(fin) == N, f"{name}: input {len(fin)} != N {N}"
            assert len(bdet) == N, f"{name}: detected {len(bdet)} != N {N}"
            oracles.append(f"""    internal static class {name}
    {{
        // codec2's own decode oracle: feed Input (N LLRs) to the decoder; hard decisions == Detected.
        public static readonly float[] Input =
        {{
{emit_floats(fin)}
        }};

        public static readonly byte[] Detected =
        {{
{emit_bytes(bdet)}
        }};
    }}""")

    hdr = ("// <auto-generated> Generated by tools/gen-ldpc-tables/gen.py from codec2 1.2.0 (git 310777b),\n"
           "// LGPL-2.1 — see docs/ofdm-design.md §1.4 and PROVENANCE.md. Do not edit by hand. </auto-generated>\n")

    tpath = os.path.join(root, "src/Packet.SoundModem/Fec/Ldpc/LdpcTables.g.cs")
    os.makedirs(os.path.dirname(tpath), exist_ok=True)
    with open(tpath, "w") as f:
        f.write(hdr + "\nnamespace Packet.SoundModem.Fec.Ldpc;\n\n")
        f.write("internal static class LdpcTables\n{\n")
        f.write("\n\n".join(tables))
        f.write("\n}\n")
    print("wrote", tpath, "-", len(CODES), "codes")

    opath = os.path.join(root, "tests/Packet.SoundModem.Tests/Fec/Ldpc/LdpcOracle.g.cs")
    os.makedirs(os.path.dirname(opath), exist_ok=True)
    with open(opath, "w") as f:
        f.write(hdr + "\nnamespace Packet.SoundModem.Tests.Fec.Ldpc;\n\n")
        f.write("internal static class LdpcOracle\n{\n")
        f.write("\n\n".join(oracles))
        f.write("\n}\n")
    print("wrote", opath, "-", len(oracles), "oracle vectors")


if __name__ == "__main__":
    main()
