using Packet.SoundModem.Audio;
using Packet.SoundModem.Hdlc;
using Packet.SoundModem.Il2p;
using Packet.SoundModem.Modems;

namespace Packet.SoundModem.Tests.Modems;

/// <summary>
/// Cross-implementation regression fixtures: WAVs generated by Dire Wolf's
/// <c>gen_packets -r 12000</c> (and <c>-I 1</c> for IL2P). Decoding audio produced by an
/// independent implementation guards against self-consistent-but-wrong modem behaviour
/// that loopback tests cannot catch. Dire Wolf's own <c>atest</c> decodes 4/4 from both
/// files; so must we. (Note the IL2P file also exercises tolerance of Dire Wolf setting
/// the RESERVED header bit that the spec's examples leave clear.)
/// </summary>
public class DirewolfCrossValidationTests
{
    private static string Fixture(string name) =>
        Path.Combine(AppContext.BaseDirectory, "Fixtures", name);

    private static float[] WithFlushTail(float[] samples, int sampleRate)
    {
        Array.Resize(ref samples, samples.Length + sampleRate / 2);
        return samples;
    }

    [Fact]
    public void All_Four_Direwolf_Afsk_Frames_Decode()
    {
        var (samples, sampleRate) = WavFile.ReadMono(Fixture("direwolf-afsk1200-4frames.wav"));

        var frames = new List<byte[]>();
        var deframer = new HdlcDeframer(frames.Add);
        var nrzi = new NrziDecoder();
        var demodulator = new AfskDemodulator(sampleRate, level => deframer.PushBit(nrzi.Decode(level)));
        demodulator.Process(WithFlushTail(samples, sampleRate));

        frames.Should().HaveCount(4);
        foreach (byte[] frame in frames)
        {
            System.Text.Encoding.ASCII.GetString(frame)
                .Should().Contain("The quick brown fox jumps over the lazy dog!");
        }
    }

    [Fact]
    public void All_Four_Direwolf_Il2p_Frames_Decode()
    {
        var (samples, sampleRate) = WavFile.ReadMono(Fixture("direwolf-il2p-afsk1200-4frames.wav"));

        var frames = new List<byte[]>();
        // IL2P over AFSK carries raw bits (no NRZI, mark = '1'), per the spec symbol map.
        var deframer = new Il2pDeframer((frame, _) => frames.Add(frame), crcMode: false);
        var demodulator = new AfskDemodulator(sampleRate, deframer.PushBit);
        demodulator.Process(WithFlushTail(samples, sampleRate));

        frames.Should().HaveCount(4);
        foreach (byte[] frame in frames)
        {
            System.Text.Encoding.ASCII.GetString(frame)
                .Should().Contain("The quick brown fox jumps over the lazy dog!");
        }
    }

    [Fact]
    public void All_Four_Direwolf_Classic_9600_Frames_Decode()
    {
        var (samples, sampleRate) = WavFile.ReadMono(Fixture("direwolf-fsk9600-4frames.wav"));

        var frames = new List<byte[]>();
        var modem = FskModem.Fsk9600(sampleRate, frames.Add, FskFraming.ClassicHdlc);
        modem.Process(WithFlushTail(samples, sampleRate));

        frames.Should().HaveCount(4);
    }

    [Fact]
    public void All_Four_Direwolf_Il2p_9600_Frames_Decode()
    {
        // Dire Wolf's 9600 IL2P baseband is inverted relative to ours; the deframer's
        // polarity-agnostic sync hunt (spec-recommended) must absorb that.
        var (samples, sampleRate) = WavFile.ReadMono(Fixture("direwolf-il2p-fsk9600-4frames.wav"));

        var frames = new List<byte[]>();
        var modem = new FskModem(sampleRate, frames.Add, FskFraming.Il2p);
        modem.Process(WithFlushTail(samples, sampleRate));

        frames.Should().HaveCount(4);
    }

    [Fact]
    public void All_Four_Direwolf_Fx25_Frames_Decode_Via_The_Fx25_Path()
    {
        var (samples, sampleRate) = WavFile.ReadMono(Fixture("direwolf-fx25-afsk1200-4frames.wav"));

        var frames = new List<byte[]>();
        var deframer = new Packet.SoundModem.Fx25.Fx25Deframer((frame, _) => frames.Add(frame));
        var nrzi = new NrziDecoder();
        var demodulator = new AfskDemodulator(sampleRate, level => deframer.PushBit(nrzi.Decode(level)));
        demodulator.Process(WithFlushTail(samples, sampleRate));

        frames.Should().HaveCount(4);
    }
}
