using Packet.SoundModem.Ofdm;
using Xunit.Abstractions;

namespace Packet.SoundModem.Tests.Ofdm;

/// <summary>
/// Validation of the FreeDV datac <b>burst-mode</b> acquisition path (codec2
/// <c>ofdm_sync_search_burst</c> / <c>ofdm_sync_state_machine_data_burst</c>) — the framing the
/// standard CLI tools (<c>freedv_data_raw_tx/rx</c>) and FreeDATA exchange:
/// <c>[silence][preamble][packets…][postamble][silence]</c> per burst, acquired by correlating
/// against the known preamble/postamble instead of the pilots. The decisive fixtures
/// (<c>samples/freedv/datac0_burst.s16</c> etc.) were generated by codec2 1.2.0's own
/// <c>freedv_data_raw_tx</c> and verified decodable by its <c>freedv_data_raw_rx</c> — see
/// <c>samples/freedv/PROVENANCE.md</c> for the exact commands and hashes.
/// </summary>
public class DatacBurstTests(ITestOutputHelper output)
{
    /// <summary>The deterministic per-packet payload the fixtures carry — the same formula the
    /// fixture inputs were generated with (PROVENANCE.md) and the round-trip tests use.</summary>
    private static byte[] Payload(int nbytes, int packet)
    {
        var p = new byte[nbytes];
        for (int i = 0; i < nbytes; i++)
        {
            p[i] = (byte)(((packet * 31) + (i * 17) + 5) & 0xff);
        }

        return p;
    }

    /// <summary>Asserts every burst's payload was recovered, in order, with a valid CRC.</summary>
    private static void AssertAllPayloadsRecovered(
        IReadOnlyList<byte[]> sent, IReadOnlyList<DatacRxResult> results)
    {
        results.Should().HaveCount(sent.Count);
        for (int i = 0; i < sent.Count; i++)
        {
            results[i].CrcOk.Should().BeTrue($"packet {i} must pass CRC");
            results[i].Payload.SequenceEqual(sent[i]).Should().BeTrue($"packet {i} payload must match");
        }
    }

    // ---------------------------------------------------------------------------------------
    // The decisive interop direction: codec2's own freedv_data_raw_tx audio → our burst RX.
    // ---------------------------------------------------------------------------------------

    [Fact]
    public void Decodes_Codec2_Freedv_Data_Raw_Tx_Datac0_Bursts()
    {
        // 5 bursts of 1 datac0 packet each, exactly as `freedv_data_raw_tx datac0 in.bin out.s16`
        // emits them (preamble + packet + postamble + 2 packets of silence per burst). codec2's
        // own freedv_data_raw_rx decodes 5/5; a faithful port must match.
        short[] samples = ReadS16("datac0_burst.s16");
        var sent = Enumerable.Range(0, 5).Select(p => Payload(14, p)).ToList();

        var rx = new DatacReceiver(OfdmMode.Datac0, packetsPerBurst: 1);
        IReadOnlyList<DatacRxResult> results = rx.Process(samples);
        output.WriteLine(
            $"datac0 burst clean: decoded {results.Count}, {results.Count(r => r.CrcOk)} CRC-OK, " +
            $"pre={rx.Demod.PreambleDetections} post={rx.Demod.PostambleDetections} uwFails={rx.Demod.UwFails}");

        AssertAllPayloadsRecovered(sent, results);
        rx.Demod.PreambleDetections.Should().Be(5, "every burst must be acquired via its preamble");
    }

    [Fact]
    public void Decodes_Codec2_Freedv_Data_Raw_Tx_Datac0_Bursts_Through_Noisy_Offset_Channel()
    {
        // The same 5 bursts through codec2's `ch` channel simulator: +22 Hz carrier offset and
        // AWGN at SNR3k ≈ 4.6 dB (see PROVENANCE.md). codec2's freedv_data_raw_rx decodes 5/5.
        short[] samples = ReadS16("datac0_burst_ch.s16");
        var sent = Enumerable.Range(0, 5).Select(p => Payload(14, p)).ToList();

        var rx = new DatacReceiver(OfdmMode.Datac0, packetsPerBurst: 1);
        IReadOnlyList<DatacRxResult> results = rx.Process(samples);
        int crcOk = results.Count(r => r.CrcOk);
        output.WriteLine(
            $"datac0 burst ch(+22Hz, ~4.6dB): decoded {results.Count}, {crcOk} CRC-OK, " +
            $"pre={rx.Demod.PreambleDetections} post={rx.Demod.PostambleDetections} uwFails={rx.Demod.UwFails}");

        // Statistical tier: assert nearly all packets, and that every CRC-OK payload is correct.
        crcOk.Should().BeGreaterThanOrEqualTo(4, "codec2's own RX decodes 5/5 at this SNR/offset");
        int next = 0;
        foreach (DatacRxResult r in results.Where(r => r.CrcOk))
        {
            while (next < sent.Count && !r.Payload.SequenceEqual(sent[next]))
            {
                next++;
            }

            next.Should().BeLessThan(sent.Count, "a CRC-valid packet must carry a transmitted payload");
            next++;
        }
    }

    [Fact]
    public void Decodes_Codec2_Freedv_Data_Raw_Tx_Datac3_Bursts()
    {
        // datac3 exercises the same acquisition with different geometry (Np=29, 126-byte payload).
        short[] samples = ReadS16("datac3_burst.s16");
        var sent = Enumerable.Range(0, 2).Select(p => Payload(126, p)).ToList();

        var rx = new DatacReceiver(OfdmMode.Datac3, packetsPerBurst: 1);
        IReadOnlyList<DatacRxResult> results = rx.Process(samples);
        output.WriteLine(
            $"datac3 burst clean: decoded {results.Count}, {results.Count(r => r.CrcOk)} CRC-OK, " +
            $"pre={rx.Demod.PreambleDetections} post={rx.Demod.PostambleDetections}");

        AssertAllPayloadsRecovered(sent, results);
    }

    // ---------------------------------------------------------------------------------------
    // The narrow RX-BPF modes (datac4/13/14): codec2's own freedv_data_raw_tx audio → our RX.
    // These are the Phase-2 decisive vectors — every one was verified byte-exactly decodable
    // by codec2's own freedv_data_raw_rx before check-in (PROVENANCE: samples/freedv/README.md).
    // ---------------------------------------------------------------------------------------

    /// <summary>Clean codec2 bursts through the RX band-pass path — datac4/13/14 exercise the
    /// <c>filtP200S400</c> RX BPF (tuned to 1468.75 / 1500 / 1472.22&#160;Hz), the shortened
    /// LDPC codes, and datac14's non-power-of-two geometry (M&#160;=&#160;144). codec2's own RX
    /// decodes each stream exactly; a faithful port must match.</summary>
    [Theory]
    [InlineData("datac4", 54, 2)]
    [InlineData("datac13", 14, 2)]
    [InlineData("datac14", 3, 5)]
    public void Decodes_Codec2_Freedv_Data_Raw_Tx_Narrow_Mode_Bursts(string modeName, int payloadBytes, int bursts)
    {
        short[] samples = ReadS16($"{modeName}_burst.s16");
        var sent = Enumerable.Range(0, bursts).Select(p => Payload(payloadBytes, p)).ToList();

        var rx = new DatacReceiver(OfdmMode.ForName(modeName), packetsPerBurst: 1);
        IReadOnlyList<DatacRxResult> results = rx.Process(samples);
        output.WriteLine(
            $"{modeName} burst clean: decoded {results.Count}, {results.Count(r => r.CrcOk)} CRC-OK, " +
            $"pre={rx.Demod.PreambleDetections} post={rx.Demod.PostambleDetections} uwFails={rx.Demod.UwFails}");

        AssertAllPayloadsRecovered(sent, results);
        rx.Demod.PreambleDetections.Should().Be(bursts, "every burst must be acquired via its preamble");
    }

    /// <summary>The same codec2 bursts through its <c>ch</c> channel simulator (+22&#160;Hz
    /// carrier offset, AWGN at SNR3k ≈ 5.4-5.8&#160;dB). codec2's own RX decodes each stream
    /// exactly at this operating point; so must we — the RX BPF is in the acquisition path, so
    /// an offset landing off the 5&#160;Hz coarse grid proves the filtered timing/frequency
    /// estimation, not just the clean centre.</summary>
    [Theory]
    [InlineData("datac4", 54, 2)]
    [InlineData("datac13", 14, 2)]
    [InlineData("datac14", 3, 5)]
    public void Decodes_Codec2_Narrow_Mode_Bursts_Through_Noisy_Offset_Channel(string modeName, int payloadBytes, int bursts)
    {
        short[] samples = ReadS16($"{modeName}_burst_ch.s16");
        var sent = Enumerable.Range(0, bursts).Select(p => Payload(payloadBytes, p)).ToList();

        var rx = new DatacReceiver(OfdmMode.ForName(modeName), packetsPerBurst: 1);
        IReadOnlyList<DatacRxResult> results = rx.Process(samples);
        output.WriteLine(
            $"{modeName} burst ch(+22Hz, ~5.5dB SNR3k): decoded {results.Count}, {results.Count(r => r.CrcOk)} CRC-OK, " +
            $"pre={rx.Demod.PreambleDetections} post={rx.Demod.PostambleDetections} uwFails={rx.Demod.UwFails}");

        AssertAllPayloadsRecovered(sent, results);
    }

    // ---------------------------------------------------------------------------------------
    // Our TX → our RX round trips.
    // ---------------------------------------------------------------------------------------

    /// <summary>Builds a burst transmission as codec2's <c>freedv_data_raw_tx</c> frames it:
    /// leading silence, then per burst the modulated <c>[preamble][packets][postamble]</c>
    /// followed by two packets' worth of silence ("just enough silence at the end of burst to
    /// allow demod to complete processing", <c>freedv_data_raw_tx.c:351-353</c>). An optional
    /// carrier offset is applied as a phase-continuous complex rotation before taking the real
    /// part (the proper SSB shift — a real-only multiply would fold in a −foff image).</summary>
    private static short[] BuildBurstStream(OfdmMode mode, IReadOnlyList<byte[][]> bursts, double foffHz = 0.0)
    {
        var tx = new DatacTransmitter(mode);
        int silence = 2 * mode.SamplesPerPacket;
        var audio = new List<Cf>();
        audio.AddRange(new Cf[silence]);
        foreach (byte[][] burst in bursts)
        {
            audio.AddRange(tx.ModulateBurst(burst));
            audio.AddRange(new Cf[silence]);
        }

        double dphi = 2.0 * Math.PI * foffHz / mode.Fs;
        var samples = new short[audio.Count];
        for (int i = 0; i < audio.Count; i++)
        {
            double phase = dphi * i;
            double rr = (audio[i].Re * Math.Cos(phase)) - (audio[i].Im * Math.Sin(phase));
            double v = Math.Round(rr, MidpointRounding.AwayFromZero);
            samples[i] = v >= 32767.0 ? (short)32767 : v <= -32768.0 ? (short)-32768 : (short)v;
        }

        return samples;
    }

    [Fact]
    public void RoundTrips_Datac0_Single_Packet_Bursts()
    {
        const int n = 10;
        var mode = OfdmMode.Datac0;
        var payloads = Enumerable.Range(0, n).Select(p => Payload(14, p)).ToList();
        short[] stream = BuildBurstStream(mode, payloads.Select(p => new[] { p }).ToList());

        var rx = new DatacReceiver(mode, packetsPerBurst: 1);
        IReadOnlyList<DatacRxResult> results = rx.Process(stream);
        output.WriteLine(
            $"datac0 10×1 bursts: decoded {results.Count}, {results.Count(r => r.CrcOk)} CRC-OK, " +
            $"pre={rx.Demod.PreambleDetections} post={rx.Demod.PostambleDetections} uwFails={rx.Demod.UwFails}");

        AssertAllPayloadsRecovered(payloads, results);
    }

    [Fact]
    public void RoundTrips_Datac0_MultiPacket_Burst()
    {
        // One burst carrying 3 packets, received with packetsPerBurst=3 — the framesperburst>1
        // shape (freedv_data_raw_tx --framesperburst). Sync must hold across packet boundaries
        // and drop (with the buffer cleared) only after the 3rd.
        var mode = OfdmMode.Datac0;
        var payloads = Enumerable.Range(0, 3).Select(p => Payload(14, p)).ToList();
        short[] stream = BuildBurstStream(mode, [[.. payloads]]);

        var rx = new DatacReceiver(mode, packetsPerBurst: 3);
        IReadOnlyList<DatacRxResult> results = rx.Process(stream);
        output.WriteLine(
            $"datac0 1×3 burst: decoded {results.Count}, {results.Count(r => r.CrcOk)} CRC-OK, " +
            $"pre={rx.Demod.PreambleDetections} post={rx.Demod.PostambleDetections}");

        AssertAllPayloadsRecovered(payloads, results);
        rx.Demod.PreambleDetections.Should().Be(1, "one burst, one preamble acquisition");
    }

    [Fact]
    public void RoundTrips_Datac3_Single_Packet_Bursts()
    {
        const int n = 3;
        var mode = OfdmMode.Datac3;
        var payloads = Enumerable.Range(0, n).Select(p => Payload(126, p)).ToList();
        short[] stream = BuildBurstStream(mode, payloads.Select(p => new[] { p }).ToList());

        var rx = new DatacReceiver(mode, packetsPerBurst: 1);
        IReadOnlyList<DatacRxResult> results = rx.Process(stream);
        output.WriteLine(
            $"datac3 3×1 bursts: decoded {results.Count}, {results.Count(r => r.CrcOk)} CRC-OK");

        AssertAllPayloadsRecovered(payloads, results);
    }

    /// <summary>Self round trips for the narrow RX-BPF modes, clean and with a carrier offset
    /// off the coarse acquisition grid — our TX's persistent BPF chain against our RX's
    /// persistent RX BPF, per mode.</summary>
    [Theory]
    [InlineData("datac4", 54, 3, 0.0)]
    [InlineData("datac4", 54, 3, 33.0)]
    [InlineData("datac13", 14, 3, 0.0)]
    [InlineData("datac13", 14, 3, 33.0)]
    [InlineData("datac14", 3, 5, 0.0)]
    [InlineData("datac14", 3, 5, 33.0)]
    public void RoundTrips_Narrow_Mode_Single_Packet_Bursts(string modeName, int payloadBytes, int n, double foffHz)
    {
        var mode = OfdmMode.ForName(modeName);
        var payloads = Enumerable.Range(0, n).Select(p => Payload(payloadBytes, p)).ToList();
        short[] stream = BuildBurstStream(mode, payloads.Select(p => new[] { p }).ToList(), foffHz);

        var rx = new DatacReceiver(mode, packetsPerBurst: 1);
        IReadOnlyList<DatacRxResult> results = rx.Process(stream);
        output.WriteLine(
            $"{modeName} {n}×1 bursts foff={foffHz:+0;-0;0} Hz: decoded {results.Count}, " +
            $"{results.Count(r => r.CrcOk)} CRC-OK, pre={rx.Demod.PreambleDetections} uwFails={rx.Demod.UwFails}");

        AssertAllPayloadsRecovered(payloads, results);
    }

    [Fact]
    public void RoundTrips_Datac0_Bursts_With_Carrier_Frequency_Offset()
    {
        // +33 Hz — inside the burst correlator's ±50 Hz search range (codec2 fmin/fmax defaults)
        // but off the 5 Hz coarse grid, so the fine 1 Hz refinement must do real work.
        const int n = 5;
        const double foffHz = 33.0;
        var mode = OfdmMode.Datac0;
        var payloads = Enumerable.Range(0, n).Select(p => Payload(14, p)).ToList();
        short[] stream = BuildBurstStream(mode, payloads.Select(p => new[] { p }).ToList(), foffHz);

        var rx = new DatacReceiver(mode, packetsPerBurst: 1);
        IReadOnlyList<DatacRxResult> results = rx.Process(stream);
        int crcOk = results.Count(r => r.CrcOk);
        output.WriteLine($"datac0 5×1 bursts +33 Hz: decoded {results.Count}, {crcOk} CRC-OK");

        crcOk.Should().Be(n, "a +33 Hz offset is inside the ±50 Hz burst search range");
        foreach (DatacRxResult r in results.Where(r => r.CrcOk))
        {
            byte[] got = r.Payload.ToArray();
            payloads.Should().ContainEquivalentOf(got, "any CRC-valid packet must carry a transmitted payload");
        }
    }

    // ---------------------------------------------------------------------------------------
    // The pdn end-of-burst extension: variable-length bursts against a max packets-per-burst.
    // ---------------------------------------------------------------------------------------

    [Fact]
    public void Variable_Length_Bursts_Decode_With_End_Of_Burst_Detection()
    {
        // The FreeDvDatacModem shape: the receiver does not know each burst's packet count,
        // so it sets packetsPerBurst to a ceiling and ends each burst via the UW check on
        // the frames after the last real packet (EndOfBurstUwDrop) with the CRC backstop.
        // Bursts of 2, 1 and 3 packets separated by only Nuwframes+1 frames of silence (the
        // modem's guard budget) — far less than codec2's two packets — must all decode, each
        // burst acquired by its own preamble.
        var mode = OfdmMode.Datac0;
        var tx = new DatacTransmitter(mode);
        var bursts = new List<byte[][]>
        {
            new[] { Payload(14, 0), Payload(14, 1) },
            new[] { Payload(14, 2) },
            new[] { Payload(14, 3), Payload(14, 4), Payload(14, 5) },
        };

        var rx = new DatacReceiver(mode, packetsPerBurst: 32, endOfBurstDetection: true);
        int gap = (rx.Demod.Nuwframes + 1) * mode.SamplesPerFrame;
        var audio = new List<Cf>(new Cf[gap]);
        foreach (byte[][] burst in bursts)
        {
            audio.AddRange(tx.ModulateBurst(burst));
            audio.AddRange(new Cf[gap]);
        }

        audio.AddRange(new Cf[2 * mode.SamplesPerPacket]);   // trailing drain
        IReadOnlyList<DatacRxResult> results = rx.Process(DatacTransmitter.ToPcm16(audio.ToArray()));
        output.WriteLine(
            $"datac0 2+1+3 variable bursts: decoded {results.Count}, {results.Count(r => r.CrcOk)} CRC-OK, " +
            $"pre={rx.Demod.PreambleDetections} eobDrops={rx.Demod.EndOfBurstDrops} uwFails={rx.Demod.UwFails}");

        var sent = Enumerable.Range(0, 6).Select(p => Payload(14, p)).ToList();
        AssertAllPayloadsRecovered(sent, results);
        rx.Demod.PreambleDetections.Should().Be(3, "each burst must be acquired via its own preamble");
        results.Select(r => r.PacketInBurst).Should().Equal(0, 1, 0, 0, 1, 2);
    }

    // ---------------------------------------------------------------------------------------
    // The postamble path: acquiring a packet whose preamble the search never saw.
    // ---------------------------------------------------------------------------------------

    [Fact]
    public void Recovers_Second_Packet_Via_Postamble_When_Receiver_Expects_Single_Packet_Bursts()
    {
        // TX sends one burst of TWO packets; the receiver is configured for one packet per burst.
        // After packet 1 decodes, sync drops and the buffered history is cleared, so packet 2's
        // frames flow past in search state — only the postamble detector can recover it: it spots
        // the known seed-3 frame, rewinds rxbufst one packet into the buffered history
        // (ofdm_sync_search_burst, ofdm.c:1355-1364) and packet 2 is demodulated from samples
        // already received. codec2 behaves identically (freedv_data_raw_rx --framesperburst 1 on
        // a --framesperburst 2 transmission decodes 2/2, the second via `nin: 0`, its postamble
        // signature); our RX decodes codec2's own such transmission 2/2 with pre=1/post=1.
        //
        // Whether the rescue lands is payload-dependent in codec2 too: packet 2's data flowing
        // through search can false-trigger the pre/post correlators first (frame-aligned data
        // shares the pilot row with the known sequences), and the resulting failed trial clears
        // the history. These payloads are a verified-rescuing pair — codec2 1.2.0's
        // freedv_data_raw_rx decodes this exact stream 2/2, and payload sets that fail here
        // (e.g. the plain Payload(14, p) pair) fail identically there, false-trial for
        // false-trial. A fully-lost preamble on a single-packet burst is NOT recoverable in
        // either implementation.
        var mode = OfdmMode.Datac0;
        static byte[] RescuePayload(int packet)
        {
            var p = new byte[14];
            for (int i = 0; i < p.Length; i++)
            {
                p[i] = (byte)((284 + (packet * 31) + (i * 17) + 5) & 0xff);
            }

            return p;
        }

        var payloads = new List<byte[]> { RescuePayload(0), RescuePayload(1) };
        short[] stream = BuildBurstStream(mode, [[.. payloads]]);

        var rx = new DatacReceiver(mode, packetsPerBurst: 1);
        IReadOnlyList<DatacRxResult> results = rx.Process(stream);
        output.WriteLine(
            $"datac0 2-packet burst, RX expects 1: decoded {results.Count}, {results.Count(r => r.CrcOk)} CRC-OK, " +
            $"pre={rx.Demod.PreambleDetections} post={rx.Demod.PostambleDetections} uwFails={rx.Demod.UwFails}");

        AssertAllPayloadsRecovered(payloads, results);
        rx.Demod.PreambleDetections.Should().Be(1, "packet 1 is acquired via the preamble");
        rx.Demod.PostambleDetections.Should().Be(1, "packet 2 can only be acquired via the postamble rewind");
        rx.Demod.UwFails.Should().Be(0, "both acquisitions must confirm their unique word first try");
    }

    [Fact]
    public void Postamble_Does_Not_Double_Decode_A_Burst_Acquired_By_Preamble()
    {
        // After a preamble-acquired burst completes, the state machine clears the buffered
        // history (ofdm.c:2202-2207) precisely so the trailing postamble cannot re-trigger a
        // decode of the same packet. 5 bursts in, exactly 5 packets out.
        short[] samples = ReadS16("datac0_burst.s16");
        var rx = new DatacReceiver(OfdmMode.Datac0, packetsPerBurst: 1);
        IReadOnlyList<DatacRxResult> results = rx.Process(samples);

        results.Count(r => r.CrcOk).Should().Be(5, "each burst must decode exactly once");
    }

    // ---------------------------------------------------------------------------------------
    // Fixture plumbing (mirrors DatacDemodTests).
    // ---------------------------------------------------------------------------------------

    private static short[] ReadS16(string name)
    {
        byte[] raw = File.ReadAllBytes(Path.Combine(SamplesDir(), name));
        var samples = new short[raw.Length / 2];
        Buffer.BlockCopy(raw, 0, samples, 0, samples.Length * 2);
        return samples;
    }

    private static string SamplesDir()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "pdn-soundmodem.slnx")))
        {
            dir = dir.Parent;
        }

        string root = dir?.FullName ?? throw new InvalidOperationException("repo root not found");
        return Path.Combine(root, "samples", "freedv");
    }
}
