using Packet.SoundModem.Dsp;
using Packet.SoundModem.Ofdm;
using Packet.SoundModem.Tests.Dsp;
using Xunit.Abstractions;

namespace Packet.SoundModem.Tests.Ofdm;

/// <summary>
/// Occupied-bandwidth guard for the datac OFDM transmitter, mirroring
/// <see cref="OccupiedBandwidthTests"/>. Each datac mode occupies roughly <c>(Nc−1)·Rs</c> of
/// carrier spread plus the pilot/clipper skirt, band-limited by the mode's TX BPF. datac0/3 ride
/// ~500 Hz, datac1 ~1.7 kHz, and the narrow datac4/13/14 a few hundred Hz — matching FreeDV's
/// published channel footprints. Measured on the real part at Fs=8000 (what
/// <c>freedv_rawdatatx</c> emits), payload symbols only.
/// </summary>
public class OfdmModulatorObwTests(ITestOutputHelper output)
{
    private const int Fs = 8000;

    // nominalHz is the carrier spread (Nc−1)·Rs; the measured 99 % OBW is that plus the pilot
    // and clipper skirt left after the mode's TX BPF, so the pinned [low,high] window sits above
    // the nominal. Values are deterministic (fixed payload, fixed meter) — this is a regression
    // guard against the modulator going wide (splatter) or collapsing (broken/DC).
    [Theory]
    [InlineData("datac0", 500, 620, 820)]
    [InlineData("datac1", 1625, 1500, 1850)]
    [InlineData("datac3", 500, 620, 820)]
    [InlineData("datac4", 188, 230, 370)]
    [InlineData("datac13", 125, 200, 330)]
    [InlineData("datac14", 167, 270, 430)]
    public void Occupied_Bandwidth_Matches_The_Mode_Footprint(
        string name, double nominalHz, double lowHz, double highHz)
    {
        var mode = OfdmMode.ForName(name);
        var mod = new OfdmModulator(mode);

        // A full packet of pseudo-random payload bits, real part only.
        byte[] bits = new byte[mode.BitsPerPacket];
        var rng = new Random(101);
        for (int i = 0; i < bits.Length; i++)
        {
            bits[i] = (byte)(rng.Next() & 1);
        }

        Cf[] tx = mod.ModulatePacketBits(bits);
        float[] real = Array.ConvertAll(tx, s => s.Re);

        int fftSize = 2048;
        var (loEdge, hiEdge, width, peak) =
            OccupiedBandwidth.Measure(real, Fs, fftSize: fftSize);

        output.WriteLine(
            $"{name}: OBW={width:F0} Hz  [{loEdge:F0}..{hiEdge:F0}]  peak={peak:F0} Hz  (nominal ~{nominalHz})");

        width.Should().BeInRange(lowHz, highHz,
            "mode {0} occupies ~{1} Hz ((Nc-1)*Rs + skirt)", name, nominalHz);

        // The lobe sits around the carrier centre (BPF centre), not aliased.
        peak.Should().BeInRange(mod.BpfCentreHz - 400, mod.BpfCentreHz + 400);
    }

    /// <summary>
    /// The rule (Tom, 2026-07-16, mirroring the NinoTNC "never wider than the TNC we share a
    /// channel with" discipline): <b>our transmission must never be wider than FreeDV's own.</b>
    /// Measured like-for-like at test time: codec2's checked-in reference packet
    /// (<c>{mode}_packet.s16</c>, generated by libcodec2 itself) vs our packet for the
    /// <i>identical</i> seed-1 LCG payload, same meter, same FFT. Tolerance is one FFT bin —
    /// the 99 %-power edge can wobble a bin under the &lt;1 LSB waveform difference. All six
    /// modes carry a checked-in codec2 <c>{mode}_packet.s16</c> vector (datac4/13 landed with
    /// Phase 2).
    /// </summary>
    [Theory]
    [InlineData("datac0")]
    [InlineData("datac1")]
    [InlineData("datac3")]
    [InlineData("datac4")]
    [InlineData("datac13")]
    [InlineData("datac14")]
    public void Never_Wider_Than_FreeDVs_Own_Transmission(string name)
    {
        var mode = OfdmMode.ForName(name);
        var mod = new OfdmModulator(mode);
        const int fftSize = 2048;
        double binHz = (double)Fs / fftSize;

        // codec2's own transmission of this packet, measured at test time.
        float[] reference = Array.ConvertAll(LoadS16(Sample($"{name}_packet.s16")), s => (float)s);
        var (_, _, refWidth, _) = OccupiedBandwidth.Measure(reference, Fs, fftSize: fftSize);

        // Ours, for the identical payload.
        byte[] bits = OfdmTxTables.LcgBits(mode.BitsPerPacket, 1);
        float[] mine = Array.ConvertAll(mod.ModulatePacketBits(bits), s => s.Re);
        var (_, _, myWidth, _) = OccupiedBandwidth.Measure(mine, Fs, fftSize: fftSize);

        output.WriteLine($"{name}: ours={myWidth:F1} Hz vs FreeDV={refWidth:F1} Hz (bin {binHz:F1} Hz)");

        myWidth.Should().BeLessThanOrEqualTo(refWidth + binHz,
            "our {0} transmission must never be wider than FreeDV's own", name);
    }

    private static short[] LoadS16(string path)
    {
        byte[] raw = File.ReadAllBytes(path);
        var samples = new short[raw.Length / 2];
        Buffer.BlockCopy(raw, 0, samples, 0, samples.Length * 2);
        return samples;
    }

    private static string Sample(string name) =>
        Path.Combine(FindRepoRoot(), "samples", "freedv", name);

    private static string FindRepoRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "pdn-soundmodem.slnx")))
        {
            dir = dir.Parent!;
        }

        return dir!.FullName;
    }
}
