<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>sm-iqcapture</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ZstdSharp.Port" />
    <PackageReference Include="M0LTE.Dsp" />
  </ItemGroup>

  <ItemGroup>
    <!-- WavFile IO for the `convert` subcommand. -->
    <ProjectReference Include="../../src/Packet.SoundModem/Packet.SoundModem.csproj" />
  </ItemGroup>

</Project>
